### ISSUE TITLE
Provide download package in release tab

### ISSUE THREAD

**Issue by quaff** [ddekany/jbosstools-freemarker#1]
such as `org.jboss.ide.eclipse.freemarker_1.5.302.v20171212-1534.jar`

**Comment by ddekany** [comment]
I have added `freemarker.site-1.5.303.zip` to the release. Eclipse supports installing directly from such archive. Or is the jar better?

**Comment by quaff** [comment]
Thanks, update site is much better, but this version still not supports code assistance for lambda such as `filter`?

**Comment by ddekany** [comment]
If you press `?` and wait, this version doesn't show `filter` in that list, if that's what you mean. That I have fixed since then, but not released. Of course, you can still use `?filter`, it won't be marked as an error.

**Comment by quaff** [comment]
Yes, that's what I mean, I'm expecting next release, thanks very much.

**Comment by ddekany** [comment]
Fix released.
