### ISSUE TITLE
Eclipse update site does not work

### ISSUE THREAD

**Issue by gpennella-sysgo** [ddekany/jbosstools-freemarker#7]
http://dl.bintray.com/freemarker/freemarker-ide/ does not work as update site.
If I try to connect with a browser, it say "Forbidden!". If I try via ECLIPSE the error is: "No repository found at http://dl.bintray.com/freemarker/freemarker-ide/."

Pls check the permissions on the site.

Thanks.

**Comment by ddekany** [comment]
Yes, because JFrog has ended the Bintray service. I'm not yet sure where should I host the update site now. But meanwhile, the update site can be downloaded from [https://github.com/ddekany/jbosstools-freemarker/releases](https://github.com/ddekany/jbosstools-freemarker/releases).

**Comment by gpennella-sysgo** [comment]
OK ! Thanks. Please note that in ECLIPSE 2021-03 FreeMarker IDE install nicely, while Jboss part not.
I have installed via the ZIP file downloaded from the releases directory you mentioned.

Thanks for support.

GP.

**Comment by ddekany** [comment]
Yeah, it's kind of messy. Like Forbidden instead of 404 is weird too. But they said that all will be deleted in coming days/weeks anyway.

**Comment by glhez** [comment]
Hello,

A ZIP Update Site is not really practical when using Oomph (which can't download plugins from ZIP directly).
If you seek a solution, you may look at what I've done for my own plugins: https://github.com/glhez/eclipse-plugins/blob/master/.travis.yml

At the end of the build, I simply copy the content of the update site to the GitHub site making available at https://glhez.github.io/eclipse-plugins/
Travis does that (but ... is sadly also going "down" like bintray) or you can do that manually using a dedicated bash script (this should work to some extends):

```bash
#!/bin/bash
declare TARGET_DIR=../jbosstools-freemarker-gh-pages
set -e
[[ ! -d "${TARGET_DIR}" ]] && git worktree add "${TARGET_DIR}" gh-pages
rm -Rfv "${TARGET_DIR}/update-site"
cp -Rfv "path/to/target/repository" "${TARGET_DIR}/update-site"
pushd "${TARGET_DIR}"
git add update-site
git commit -m 'update site'
git push origin
popd
```
The idea is to copy the whole p2 repository to the gh-pages branch.

This use a worktree but you could also clone another copy directly.

**Comment by mauromol** [comment]
Others are indeed publishing now to GitHub pages: https://github.com/checkstyle/eclipse-cs/issues/279

**Comment by ddekany** [comment]
Yes, eventually I will get to it, and update the build to do that.

**Comment by wicketr** [comment]
Until then, what is the manual process for installing the plugin from the release ZIP file?

**Comment by ddekany** [comment]
You can use this update site, thanks to the PR of @glhez: http://ddekany.github.io/jbosstools-freemarker/updates/
Will test with more Eclipse and update this on Eclipse Marketplace.

**Comment by ddekany** [comment]
New version was published no Eclipse Marketplace.
